
#ifndef MCTYXBLD_H
#define MCTYXBLD_H

/* This header may change to be more descriptive later. */

/* Residential, 1x1 */

#define XBLD_RES_1X1_LOWER_CLASS_HOME_0 0x70
#define XBLD_RES_1X1_LOWER_CLASS_HOME_1 0x71
#define XBLD_RES_1X1_LOWER_CLASS_HOME_2 0x72
#define XBLD_RES_1X1_LOWER_CLASS_HOME_3 0x73
#define XBLD_RES_1X1_MIDDLE_CLASS_HOME_0 0x74
#define XBLD_RES_1X1_MIDDLE_CLASS_HOME_1 0x75
#define XBLD_RES_1X1_MIDDLE_CLASS_HOME_2 0x76
#define XBLD_RES_1X1_MIDDLE_CLASS_HOME_3 0x77
#define XBLD_RES_1X1_LUXURY_HOMES 0x78

/* Commercial, 1x1 */

#define XBLD_COM_1X1_GAS_STATION_0 0x7C
#define XBLD_COM_1X1_BED_BREAKFAST_INN 0x7D
#define XBLD_COM_1X1_CONVENIENCE_STORE 0x7E
#define XBLD_COM_1X1_GAS_STATION_1 0x7F
#define XBLD_COM_1X1_SMALL_OFFICE_BUILDING 0x80
#define XBLD_COM_1X1_OFFICE_BUILDING 0x81
#define XBLD_COM_1X1_WAREHOUSE 0x82
#define XBLD_COM_1X1_CASSIDYS_TOY_STORE 0x83

/* Industrial, 1x1 */

#define XBLD_IND_1X1_WAREHOUSE_0 0x84
#define XBLD_IND_1X1_CHEMICAL_STORAGE 0x85
#define XBLD_IND_1X1_WAREHOUSE_1 0x86
#define XBLD_IND_1X1_INDUSTRIAL_SUBSTATION 0x87

/* Miscellaneous, 1x1 */

#define XBLD_MISC_1X1_CONSTRUCTION_0 0x88
#define XBLD_MISC_1X1_CONSTRUCTION_1 0x89
#define XBLD_MISC_1X1_ABANDONED_BUILDING_0 0x8A
#define XBLD_MISC_1X1_ABANDONED_BUILDING_1 0x8B

/* Residential, 2x2 */

#define XBLD_RES_2X2_CHEAP_APARTMENTS 0x8C
#define XBLD_RES_2X2_APARTMENTS_0 0x8D
#define XBLD_RES_2X2_APARTMENTS_1 0x8E
#define XBLD_RES_2X2_NICE_APARTMENTS_0 0x8F
#define XBLD_RES_2X2_NICE_APARTMENTS_1 0x90
#define XBLD_RES_2X2_CONDOMINIUM_0 0x91
#define XBLD_RES_2X2_CONDOMINIUM_1 0x92
#define XBLD_RES_2X2_CONDOMINIUM_2 0x93

/* Commercial, 2x2 */

#define XBLD_COM_2X2_SHOPPING_CENTER 0x94
#define XBLD_COM_2X2_GROCERY_STORE 0x95
#define XBLD_COM_2X2_OFFICE_BUILDING_0 0x96
#define XBLD_COM_2X2_RESORT_HOTEL 0x97
#define XBLD_COM_2X2_OFFICE_BUILDING_1 0x98
#define XBLD_COM_2X2_OFFICE_RETAIL 0x99
#define XBLD_COM_2X2_OFFICE_BUILDING_2 0x9A
#define XBLD_COM_2X2_OFFICE_BUILDING_3 0x9B
#define XBLD_COM_2X2_OFFICE_BUILDING_4 0x9C
#define XBLD_COM_2X2_OFFICE_BUILDING_5 0x9D

/* Industrial, 2x2 */

#define XBLD_IND_2X2_WAREHOUSE 0x9E
#define XBLD_IND_2X2_CHEMICAL_PROCESSING 0x9F
#define XBLD_IND_2X2_FACTORY_0 0xA0
#define XBLD_IND_2X2_FACTORY_1 0xA1
#define XBLD_IND_2X2_FACTORY_2 0xA2
#define XBLD_IND_2X2_FACTORY_3 0xA3
#define XBLD_IND_2X2_FACTORY_4 0xA4
#define XBLD_IND_2X2_FACTORY_5 0xA5

/* Miscellaneous, 2x2 */

#define XBLD_MISC_2X2_CONSTRUCTION_0 0xA6
#define XBLD_MISC_2X2_CONSTRUCTION_1 0xA7
#define XBLD_MISC_2X2_CONSTRUCTION_2 0xA8
#define XBLD_MISC_2X2_CONSTRUCTION_3 0xA9
#define XBLD_MISC_2X2_ABANDONED_BUILDING_0 0xAA
#define XBLD_MISC_2X2_ABANDONED_BUILDING_1 0xAB
#define XBLD_MISC_2X2_ABANDONED_BUILDING_2 0xAC
#define XBLD_MISC_2X2_ABANDONED_BUILDING_3 0xAD

/* Residential, 3x3 */

#define XBLD_RES_3X3_LARGE_APARTMENT_BUILDING_0 0xAE
#define XBLD_RES_3X3_LARGE_APARTMENT_BUILDING_1 0xAF
#define XBLD_RES_3X3_CONDOMINIUM_0 0xB0
#define XBLD_RES_3X3_CONDOMINIUM_1 0xB1

/* Commercial, 3x3 */

#define XBLD_COM_3X3_OFFICE_PARK 0xB2
#define XBLD_COM_3X3_OFFICE_TOWER_0 0xB3
#define XBLD_COM_3X3_MINI_MALL 0xB4
#define XBLD_COM_3X3_THEATER_SQUARE 0xB5
#define XBLD_COM_3X3_DRIVE_IN_THEATER 0xB6
#define XBLD_COM_3X3_OFFICE_TOWER_1 0xB7
#define XBLD_COM_3X3_OFFICE_TOWER_2 0xB8
#define XBLD_COM_3X3_PARKING_LOT 0xB9
#define XBLD_COM_3X3_HISTORIC_OFFICE_BUILDING 0xBA
#define XBLD_COM_3X3_CORPORATE_HEADQUARTERS 0xBB

/* Industrial, 3x3 */

#define XBLD_IND_3X3_CHEMICAL_PROCESSING 0xBC
#define XBLD_IND_3X3_LARGE_FACTORY 0xBD
#define XBLD_IND_3X3_INDUSTRIAL_THINGAMAJIG 0xBE
#define XBLD_IND_3X3_FACTORY 0xBF
#define XBLD_IND_3X3_LARGE_WAREHOUSE 0xC0
#define XBLD_IND_3X3_WAREHOUSE 0xC1

/* Miscellaneous, 3x3 */

#define XBLD_IND_3X3_CONSTRUCTION_0 0xC2
#define XBLD_IND_3X3_CONSTRUCTION_1 0xC3
#define XBLD_IND_3X3_ABANDONED_BUILDING_0 0xC4
#define XBLD_IND_3X3_ABANDONED_BUILDING_1 0xC5

/* Power Plants */

#define XBLD_POWER_1X1_HYDROELECTRIC_POWER_0 0xC6
#define XBLD_POWER_1X1_HYDROELECTRIC_POWER_1 0xC7
#define XBLD_POWER_1X1_WIND_POWER 0xC8
#define XBLD_POWER_4X4_NATURAL_GAS_PLANT 0xC9
#define XBLD_POWER_4X4_OIL_PLANT 0xCA
#define XBLD_POWER_4X4_NUCLEAR_PLANT 0xCB
#define XBLD_POWER_4X4_SOLAR_PLANT 0xCC
#define XBLD_POWER_4X4_MICROWAVE_RECEIVER 0xCD
#define XBLD_POWER_4X4_FUSION_PLANT 0xCE
#define XBLD_POWER_4X4_COAL_PLANT 0xCF

/* City Services */

#define XBLD_CITY_HALL 0xD0
#define XBLD_HOSPITAL 0xD1
#define XBLD_POLICE_STATION 0xD2
#define XBLD_FIRE_STATION 0xD3
#define XBLD_MUSEUM 0xD4
#define XBLD_PARK_BIG 0xD5
#define XBLD_SCHOOL 0xD6
#define XBLD_STADIUM 0xD7
#define XBLD_PRISON 0xD8
#define XBLD_COLLEGE 0xD9
#define XBLD_ZOO 0xDA
#define XBLD_STATUE 0xDB
#define XBLD_WATER_PUMP 0xDC
#define XBLD_RUNWAY_0 0xDD
#define XBLD_RUNWAY_1 0xDE
#define XBLD_PIER 0xDF
#define XBLD_CRANE 0xE0
#define XBLD_CONTROL_TOWER_0 0xE1
#define XBLD_CONTROL_TOWER_1 0xE2
#define XBLD_SEAPORT_WAREHOUSE 0xE3
#define XBLD_AIRPORT_BUILDING_0 0xE4
#define XBLD_AIRPORT_BUILDING_1 0xE5
#define XBLD_TARMAC 0xE6
#define XBLD_F15B 0xE7
#define XBLD_HANGAR_0 0xE8
#define XBLD_SUBWAY_STATION 0xE9
#define XBLD_RADAR 0xEA
#define XBLD_WATER_TOWER 0xEB
#define XBLD_BUS_STATION 0xEC
#define XBLD_RAIL_STATION 0xED
#define XBLD_PARKING_LOT_0 0xEE
#define XBLD_PARKING_LOT_1 0xEF
#define XBLD_LOADING_BAY 0xF0
#define XBLD_TOP_SECRET 0xF1
#define XBLD_CARGO_YARD 0xF2
#define XBLD_MAYORS_HOUSE 0xF3
#define XBLD_WATER_TREATMENT_PLANT 0xF4
#define XBLD_LIBRARY 0xF5
#define XBLD_HANGAR_1 0xF6
#define XBLD_CHURCH 0xF7
#define XBLD_MARINA 0xF8
#define XBLD_MISSILE_SILO 0xF9
#define XBLD_DESALINATION_PLANT 0xFA

/* Arcologies */

#define XBLD_PLYMOUTH_ARCOLOGY 0xFB
#define XBLD_FOREST_ARCOLOGY 0xFC
#define XBLD_DARCO_ARCOLOGY 0xFD
#define XBLD_LAUNCH_ARCOLOGY 0xFE

#define XBLD_BRAUN_LLAMA_DOME 0xFF

#endif /* !MCTYXBLD_H */

